apiVersion: v1
kind: ConfigMap
metadata:
  name: sekios-config
  namespace: sekios
data:
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  DB_HOST: "{{ .Values.config.database.host }}"
  DB_PORT: "{{ .Values.config.database.port }}"
